services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/ml_model:/app/ml_model
  frontend:
    build: ./frontend
    ports:
      - "80:4173"
    environment:
      - VITE_BACKEND_URL=http://209.38.224.80:8000/
    volumes:
      - ./frontend/src:/app/src